In [ ]:
# Manufacturing Sales Analytics

## End-to-End Data Analytics Portfolio Project

### Project Objective

The objective of this project is to analyze the sales performance of a manufacturing company and identify the main drivers of revenue, profitability, customer performance, product performance, and payment behavior.

### Business Questions

1. How are sales and profitability changing over time?
2. Which products generate the highest revenue and profit?
3. Which customers and industries are the most valuable?
4. Which regions perform best?
5. How do discounts affect profitability?
6. Which customers have poor payment behavior?
7. What factors are associated with delayed orders?

In [1]:
import pandas as pd

In [1]:
file_path = r"P:\Jafarnia\personal\Programing\manufacturing_sales_analytics.xlsx"

In [2]:
import os

print(os.path.exists(file_path))

True

In [3]:
import pandas as pd

xls = pd.ExcelFile(file_path)
xls.sheet_names

['Customers',
 'Products',
 'Orders',
 'Sales_Lines',
 'Payments',
 'Data_Dictionary']

In [4]:
customers = pd.read_excel(file_path, sheet_name="Customers")
products = pd.read_excel(file_path, sheet_name="Products")
orders = pd.read_excel(file_path, sheet_name="Orders")
sales = pd.read_excel(file_path, sheet_name="Sales_Lines")
payments = pd.read_excel(file_path, sheet_name="Payments")

In [5]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Sales:", sales.shape)
print("Payments:", payments.shape)

Customers: (500, 9)
Products: (60, 9)
Orders: (4000, 13)
Sales: (8980, 18)
Payments: (6537, 9)

In [6]:
sales.head()

,SalesLineID,OrderID,OrderDate,CustomerID,ProductID,SalesRep,SalesChannel,Quantity,UnitPrice_USD,DiscountPct,GrossSales_USD,DiscountAmount_USD,NetSales_USD,UnitCost_USD,TotalCost_USD,FreightCost_USD,GrossProfit_USD,GrossMarginPct
0,SL000001,O00001,2025-08-31,C0472,P054,Pouya Rahimi,Direct Sales,2,14364.54,0.0632,28729.08,1816.02,26913.06,7950.80,15901.60,1186.80,9824.66,0.3651
1,SL000002,O00002,2024-07-05,C0374,P024,Reza Moradi,Direct Sales,1,21357.83,0.0985,21357.83,2104.37,19253.45,12042.52,12042.52,670.69,6540.24,0.3397
2,SL000003,O00002,2024-07-05,C0374,P053,Reza Moradi,Direct Sales,2,13210.59,0.0805,26421.18,2125.67,24295.51,7727.43,15454.86,987.16,7853.49,0.3232
3,SL000004,O00003,2025-07-23,C0026,P060,Amir Hosseini,Tender,3,96642.88,0.0726,289928.64,21060.25,268868.39,72571.44,217714.32,7154.69,43999.37,0.1636
4,SL000005,O00003,2025-07-23,C0026,P008,Amir Hosseini,Tender,2,14027.59,0.1221,28055.18,3424.47,24630.71,9302.65,18605.30,469.29,5556.12,0.2256

In [7]:
customers.head()

,CustomerID,CustomerName,Industry,Segment,Region,City,RegistrationDate,CreditLimit_USD,RiskLevel
0,C0001,Cement Industrial Co. 001,Cement,Small,Central,Isfahan,2020-09-30,29968.66,Medium
1,C0002,Mining Industrial Co. 002,Mining,Enterprise,Central,Kashan,2024-08-15,248836.32,Low
2,C0003,Mining Industrial Co. 003,Mining,Medium,North,Rasht,2024-04-17,75526.77,Medium
3,C0004,Food Industrial Co. 004,Food Processing,Small,West,Hamedan,2021-02-13,44331.05,Low
4,C0005,Cement Industrial Co. 005,Cement,Small,North,Gorgan,2019-09-29,29775.19,Medium

In [8]:
orders.head()

,OrderID,ReferenceNo,OrderDate,CustomerID,SalesRep,SalesChannel,PaymentTerms,OrderStatus,PromisedDeliveryDate,ActualDeliveryDate,OrderValue_USD,OrderCost_USD,OrderDiscount_USD
0,O00001,REF-2025-00001,2025-08-31,C0472,Pouya Rahimi,Direct Sales,Advance,In Production,2025-11-07,NaN,26913.06,17088.40,1816.02
1,O00002,REF-2024-00002,2024-07-05,C0374,Reza Moradi,Direct Sales,30 Days,Delivered,2024-11-17,2024-11-06,43548.96,29155.23,4230.04
2,O00003,REF-2025-00003,2025-07-23,C0026,Amir Hosseini,Tender,30 Days,In Production,2025-10-25,NaN,293499.10,243943.60,24484.72
3,O00004,REF-2025-00004,2025-04-18,C0263,Niloofar Ahmadi,Direct Sales,30 Days,Delivered,2025-06-09,2025-06-27,57295.46,36860.30,2400.69
4,O00005,REF-2024-00005,2024-08-01,C0153,Arman Kazemi,Website,Advance,Delayed,2024-11-20,NaN,25103.53,17678.36,1238.16

In [9]:
sales.head(10)

,SalesLineID,OrderID,OrderDate,CustomerID,ProductID,SalesRep,SalesChannel,Quantity,UnitPrice_USD,DiscountPct,GrossSales_USD,DiscountAmount_USD,NetSales_USD,UnitCost_USD,TotalCost_USD,FreightCost_USD,GrossProfit_USD,GrossMarginPct
0,SL000001,O00001,2025-08-31,C0472,P054,Pouya Rahimi,Direct Sales,2,14364.54,0.0632,28729.08,1816.02,26913.06,7950.80,15901.60,1186.80,9824.66,0.3651
1,SL000002,O00002,2024-07-05,C0374,P024,Reza Moradi,Direct Sales,1,21357.83,0.0985,21357.83,2104.37,19253.45,12042.52,12042.52,670.69,6540.24,0.3397
2,SL000003,O00002,2024-07-05,C0374,P053,Reza Moradi,Direct Sales,2,13210.59,0.0805,26421.18,2125.67,24295.51,7727.43,15454.86,987.16,7853.49,0.3232
3,SL000004,O00003,2025-07-23,C0026,P060,Amir Hosseini,Tender,3,96642.88,0.0726,289928.64,21060.25,268868.39,72571.44,217714.32,7154.69,43999.37,0.1636
4,SL000005,O00003,2025-07-23,C0026,P008,Amir Hosseini,Tender,2,14027.59,0.1221,28055.18,3424.47,24630.71,9302.65,18605.30,469.29,5556.12,0.2256
5,SL000006,O00004,2025-04-18,C0263,P001,Niloofar Ahmadi,Direct Sales,1,7718.66,0.0830,7718.66,640.91,7077.75,4624.52,4624.52,175.76,2277.47,0.3218
6,SL000007,O00004,2025-04-18,C0263,P015,Niloofar Ahmadi,Direct Sales,2,25988.74,0.0339,51977.49,1759.78,50217.71,15368.78,30737.57,1322.45,18157.69,0.3616
7,SL000008,O00005,2024-08-01,C0153,P018,Arman Kazemi,Website,1,26341.69,0.0470,26341.69,1238.16,25103.53,16754.76,16754.76,923.60,7425.17,0.2958
8,SL000009,O00006,2025-04-07,C0339,P003,Sara Karimi,Direct Sales,3,10555.49,0.1168,31666.48,3698.04,27968.44,6193.77,18581.31,990.90,8396.23,0.3002
9,SL000010,O00006,2025-04-07,C0339,P038,Sara Karimi,Direct Sales,1,12332.27,0.0000,12332.27,0.00,12332.27,6719.64,6719.64,342.29,5270.33,0.4274

In [10]:
sales.columns

Index(['SalesLineID', 'OrderID', 'OrderDate', 'CustomerID', 'ProductID',
       'SalesRep', 'SalesChannel', 'Quantity', 'UnitPrice_USD', 'DiscountPct',
       'GrossSales_USD', 'DiscountAmount_USD', 'NetSales_USD', 'UnitCost_USD',
       'TotalCost_USD', 'FreightCost_USD', 'GrossProfit_USD',
       'GrossMarginPct'],
      dtype='object')

In [11]:
orders.columns

Index(['OrderID', 'ReferenceNo', 'OrderDate', 'CustomerID', 'SalesRep',
       'SalesChannel', 'PaymentTerms', 'OrderStatus', 'PromisedDeliveryDate',
       'ActualDeliveryDate', 'OrderValue_USD', 'OrderCost_USD',
       'OrderDiscount_USD'],
      dtype='object')

In [12]:
customers.columns

Index(['CustomerID', 'CustomerName', 'Industry', 'Segment', 'Region', 'City',
       'RegistrationDate', 'CreditLimit_USD', 'RiskLevel'],
      dtype='object')

In [13]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8980 entries, 0 to 8979
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   SalesLineID         8980 non-null   object
 1   OrderID             8980 non-null   object
 2   OrderDate           8980 non-null   object
 3   CustomerID          8980 non-null   object
 4   ProductID           8980 non-null   object
 5   SalesRep            8980 non-null   object
 6   SalesChannel        8980 non-null   object
 7   Quantity            8980 non-null   int64
 8   UnitPrice_USD       8980 non-null   float64
 9   DiscountPct         8960 non-null   float64
 10  GrossSales_USD      8980 non-null   float64
 11  DiscountAmount_USD  8980 non-null   float64
 12  NetSales_USD        8980 non-null   float64
 13  UnitCost_USD        8980 non-null   float64
 14  TotalCost_USD       8980 non-null   float64
 15  FreightCost_USD     8980 non-null   float64
 16  GrossProfit_USD     8980 non-null   float64
 17  GrossMarginPct      8980 non-null   float64
dtypes: float64(10), int64(1), object(7)
memory usage: 1.2+ MB

In [14]:
sales.isnull().sum()

SalesLineID            0
OrderID                0
OrderDate              0
CustomerID             0
ProductID              0
SalesRep               0
SalesChannel           0
Quantity               0
UnitPrice_USD          0
DiscountPct           20
GrossSales_USD         0
DiscountAmount_USD     0
NetSales_USD           0
UnitCost_USD           0
TotalCost_USD          0
FreightCost_USD        0
GrossProfit_USD        0
GrossMarginPct         0
dtype: int64

In [15]:
customers.isnull().sum()

CustomerID          0
CustomerName        0
Industry            0
Segment             0
Region              0
City                8
RegistrationDate    0
CreditLimit_USD     0
RiskLevel           0
dtype: int64

In [16]:
sales.duplicated().sum()

np.int64(0)

In [17]:
customers.duplicated().sum()

np.int64(0)

In [18]:
orders["OrderID"].duplicated().sum()

np.int64(0)

In [19]:
customers["CustomerID"].duplicated().sum()

np.int64(0)

In [20]:
sales["SalesLineID"].duplicated().sum()

np.int64(0)

In [21]:
sales.describe()

,Quantity,UnitPrice_USD,DiscountPct,GrossSales_USD,DiscountAmount_USD,NetSales_USD,UnitCost_USD,TotalCost_USD,FreightCost_USD,GrossProfit_USD,GrossMarginPct
count,8980.000000,8980.000000,8960.000000,8980.000000,8980.000000,8980.000000,8980.000000,8980.000000,8980.000000,8980.000000,8980.000000
mean,2.737305,21442.002344,0.071771,58372.121259,4162.879818,54209.241430,13639.899590,37114.082072,1494.714548,15600.444769,0.311218
std,2.146420,19300.677181,0.043111,78872.112754,6854.369227,73413.778417,13567.835024,53739.902610,2204.944953,18813.187378,0.062654
min,1.000000,6260.030000,0.000000,6260.030000,0.000000,5511.690000,3529.570000,3534.400000,60.390000,1090.620000,0.047100
25%,1.000000,11295.492500,0.040200,18548.655000,920.807500,17201.185000,6613.165000,10884.475000,411.060000,5238.405000,0.270900
50%,2.000000,15114.785000,0.070300,32955.300000,2111.725000,30529.225000,9059.935000,19498.650000,799.470000,9621.660000,0.315750
75%,3.000000,21890.825000,0.100700,66410.690000,4588.635000,61719.102500,14057.150000,41290.407500,1642.155000,18347.007500,0.356125
max,10.000000,102961.450000,0.220000,968780.870000,110837.670000,905071.710000,72929.930000,699098.760000,36525.750000,244783.270000,0.490500

In [22]:
total_sales = sales["NetSales_USD"].sum()

total_sales

np.float64(486798988.04)

In [23]:
total_profit = sales["GrossProfit_USD"].sum()

total_profit

np.float64(140091994.02999997)

In [24]:
overall_margin = total_profit / total_sales

overall_margin

np.float64(0.2877820157228607)

In [25]:
print(f"Total Sales: ${total_sales:,.0f}")
print(f"Total Gross Profit: ${total_profit:,.0f}")
print(f"Overall Gross Margin: {overall_margin:.1%}")

Total Sales: $486,798,988
Total Gross Profit: $140,091,994
Overall Gross Margin: 28.8%